on:
  push:
    branches:
      - main


jobs:

  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install git-cliff
        run: |
          #todo: update version number
          curl -L -o git-cliff.deb \
            https://github.com/orhun/git-cliff/releases/download/v2.3.0/git-cliff-2.3.0.deb
          sudo apt install ./git-cliff.deb

      - name: Run Changelog Script
        run: |
          ./.changelog/run.sh all

      - name: Authenticate with Githuh CLI
        run: |
          echo ${{ secrets.MY_SECRET }} | gh auth login -p https --with-token

      - name: List open PRs
        run: |
          gh pr list